CREATE TABLE BASKET AS SELECT UNIQUE BASKET_ID, BASKET_DATE, PAYMENT_TYPE, TOTAL_PRICE, TAX, NAME FROM YODA_59;

CREATE TABLE PAYPAL AS SELECT UNIQUE BASKET_ID, PAYPAL_AC_NO, PAYPAL_PASSWORD FROM YODA_59 WHERE PAYMENT_TYPE = 'Paypal';

CREATE TABLE BANK AS SELECT UNIQUE BASKET_ID, BANK_NAME, CREDIT_CARD_NO FROM YODA_59 WHERE PAYMENT_TYPE = 'Bank';

CREATE TABLE CUSTOMER AS SELECT UNIQUE NAME, ADDRESS, GENDER, COUNTRY_ID FROM YODA_59;

CREATE TABLE CUSTOMER_MALE AS SELECT UNIQUE NAME, AGE, JOB FROM YODA_59 WHERE GENDER != 'Female';

CREATE TABLE CUSTOMER_FEMALE AS SELECT UNIQUE NAME, STATUS, INCOME FROM YODA_59 WHERE GENDER = 'Female';

CREATE TABLE COUNTRY AS SELECT UNIQUE COUNTRY_ID, COUNTRY FROM YODA_59;

CREATE TABLE SELLER AS SELECT UNIQUE SELLER_ID, SELLER_NAME, SELLER_COUNTRY, SELLER_ADDRESS, RATING FROM YODA_59;

CREATE TABLE SHOP AS SELECT UNIQUE SELLER_ID, SHOP_TYPE FROM YODA_59 WHERE SHOP_TYPE != 'NULL';

CREATE TABLE FACTORY AS SELECT UNIQUE SELLER_ID, FACTORY_OWNER, CREDIT_RATING FROM YODA_59 WHERE CREDIT_RATING != 'NULL';

CREATE TABLE ITEM AS SELECT UNIQUE ITEM_ID, PRICE FROM YODA_59;

CREATE TABLE BASKET_ITEM AS SELECT UNIQUE BASKET_ITEM, BASKET_ID, ITEM_ID, SELLER_ID, WARRANTY, POSTAGE_CLASS FROM YODA_59 WHERE WARRANTY != 'NaN';

CREATE TABLE STOCK AS SELECT UNIQUE SELLER_ID, ITEM_ID, STOCK FROM YODA_XTRA59;

ALTER TABLE COUNTRY ADD CONSTRAINT PK_COUNTRY_ID PRIMARY KEY (COUNTRY_ID);

ALTER TABLE CUSTOMER ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (NAME);
ALTER TABLE CUSTOMER ADD CONSTRAINT FK_CUSTOMER FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (COUNTRY_ID);

ALTER TABLE BASKET ADD CONSTRAINT PK_BASKET PRIMARY KEY (BASKET_ID);
ALTER TABLE BASKET ADD CONSTRAINT FK_BASKET FOREIGN KEY (NAME) REFERENCES CUSTOMER (NAME);

ALTER TABLE PAYPAL ADD CONSTRAINT PK_PAYPAL PRIMARY KEY (BASKET_ID);
ALTER TABLE PAYPAL ADD CONSTRAINT FK_PAYPAL FOREIGN KEY (BASKET_ID) REFERENCES BASKET (BASKET_ID);

ALTER TABLE BANK ADD CONSTRAINT PK_BANK PRIMARY KEY (BASKET_ID);
ALTER TABLE BANK ADD CONSTRAINT FK_BANK FOREIGN KEY (BASKET_ID) REFERENCES BASKET (BASKET_ID);

ALTER TABLE CUSTOMER_MALE ADD CONSTRAINT PK_CUSTOMER_MALE PRIMARY KEY (NAME);
ALTER TABLE CUSTOMER_MALE ADD CONSTRAINT FK_CUSTOMER_MALE FOREIGN KEY (NAME) REFERENCES CUSTOMER (NAME);

ALTER TABLE CUSTOMER_FEMALE ADD CONSTRAINT PK_FEMALE PRIMARY KEY (NAME);
ALTER TABLE CUSTOMER_FEMALE ADD CONSTRAINT FK_FEMALE FOREIGN KEY (NAME) REFERENCES CUSTOMER (NAME);

ALTER TABLE SELLER ADD CONSTRAINT PK_SELLER PRIMARY KEY (SELLER_ID);

ALTER TABLE SHOP ADD CONSTRAINT PK_SHOP PRIMARY KEY (SELLER_ID);
ALTER TABLE SHOP ADD CONSTRAINT FK_SHOP FOREIGN KEY (SELLER_ID) REFERENCES SELLER (SELLER_ID);

ALTER TABLE FACTORY ADD CONSTRAINT PK_FACTORY PRIMARY KEY (SELLER_ID);
ALTER TABLE FACTORY ADD CONSTRAINT FK_FACTORY FOREIGN KEY (SELLER_ID) REFERENCES SELLER (SELLER_ID);

ALTER TABLE ITEM ADD CONSTRAINT PK_ITEM PRIMARY KEY (ITEM_ID);

ALTER TABLE BASKET_ITEM ADD CONSTRAINT PK_BASKET_ITEM PRIMARY KEY (BASKET_ITEM);
ALTER TABLE BASKET_ITEM ADD CONSTRAINT FK_BASKET_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID);
ALTER TABLE BASKET_ITEM ADD CONSTRAINT FK_BASKET_ITEM2 FOREIGN KEY (BASKET_ID) REFERENCES BASKET(BASKET_ID);
ALTER TABLE BASKET_ITEM ADD CONSTRAINT FK_BASKET_ITEM3 FOREIGN KEY (SELLER_ID) REFERENCES SELLER(SELLER_ID);

ALTER TABLE STOCK ADD CONSTRAINT FK_STOCK FOREIGN KEY (SELLER_ID) REFERENCES SELLER (SELLER_ID);
ALTER TABLE STOCK ADD CONSTRAINT FK_STOCK2 FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID);
